favicon:
  href: /icon.png # Favicon of your site.
  type: image/png # Icon type, possible values are(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

search: https://cn.bing.com/search?q= # https://www.google.com/search?q==
order_by: title # date,-date,title,url,...
head: '<!--<script src="" async></script>-->' # Add anything to <head></head>

archives:
  switch: false # true,false Switching this function.
  categories: [] # Only the categories you set will be displayed on the archive page.

menu:
  首页: /
  所有文章: archives
  关于: about

footer_link:

github:
  repo: KiritoKing/hexo-geography-blog # nexmoe/books
  edit: false # true,false
  history: false # true,false

analytics: # 统计系统，目前支持 Google analytics.js 统计、Google Tag Manager 统计、CNZZ 统计、腾讯统计、51.La统计、百度统计
  google_site_id: #<ID>
  gtags_site_id: #<ID>
  cnzz_site_id: #<ID>
  tencent_site_id: #<ID>
  la_site_id: #<ID>
  baidu_site_id: #<ID>
  gtm_container_id: #<ID>

cdn: # 这里可以修改站点使用的库的CDN
  disqusjs: 
    css: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqusjs.min.css
    js: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqus.min.js
  gitalk:
    css: https://cdn.jsdelivr.net/npm/gitalk@1.5.0/dist/gitalk.min.css
    js: https://cdn.jsdelivr.net/npm/gitalk@1.5.0/dist/gitalk.min.js
  valine:
    js: https://cdn.jsdelivr.net/npm/valine

comment: false # 评论框，目前支持 gitalk,gitment,valine,disqus,disqusjs,changyan,livere,DiscussBot,utteranc,giscuss 使用 false 可以关闭

gitalk:
  admin:  # 拥有对该repo进行操作的 GitHub username
  owner:  # 持有该 repo 的 GitHub username
  repo:  # 存放评论的 issue 所在的 repo
  clientID:  # GitHub Client ID
  clientSecret:  # GitHub Client Secret

gitment:
  owner:  # 持有该 repo 的 GitHub username
  repo:  # 存放评论的 issue 所在的 repo
  clientID:  # GitHub Client ID
  clientSecret:  # GitHub Client Secret

valine: 
  appId: <API_ID> # leancloud application app id
  appKey: <API_Key> # leancloud application app key

disqus:
  shortname: <shortname> # 你的 Disqus shortname

disqusjs:
  shortname: <shortname> # 你的 Disqus shortname
  sitename: <sitename> # 你站点的名称，将会显示在「评论基础模式」的 header 中；该配置应该和 Disqus Admin - Settings - General - Website Name 一致
  api: https://disqus.skk.moe/disqus/ # DisqusJS 请求的 API Endpoint，通常情况下你应该配置一个 Disqus API 的反代并填入反代的地址。你也可以直接使用 DISQUS 官方 API 的 Endpoint https://disqus.com/api/，或是使用SukkaW搭建的 Disqus API 反代 Endpoint https://disqus.skk.moe/disqus/。
  apikey: <api_key> # DisqusJS 向 API 发起请求时使用的 API Key，你应该在配置 Disqus Application 时获取了 API Key;DisqusJS 支持填入一个 包含多个 API Key 的 Array，在每次请求时会随机使用其中一个；如果你只需要填入一个 API Key，则可以填入 String 或 Array。
  admin: <admin> # 你的站点的 Disqus Moderator 的用户名（也就是你的用户名）。你可以在 Disqus - Settings - Account - Username 获取你的 Username
  adminLabel: <adminLabel> # 你想显示在 Disqus Moderator Badge 中的文字。该配置应和 Disqus Admin - Settings - Community - Moderator Badge Text 相同

changyan:
  appid: <APP_ID> # 畅言的 APPID
  conf: <CONF> # 畅言的 CONF
  thread_key_type: path # 可选 id 或 path

livere:
  data_uid: <data_uid> # 你的来必力 UID，可以在来必力后台获取

DiscussBot:
  id: <id> # 站点id
  comments: 5 # 可能是限制每位用户单页面评论最多条数？
  color: # 评论框主色调
  dislike: 0 # 显示差评按钮
  icons: 0 # 图标主题
  diff: 0 # 每位用户name不同颜色

utteranc: # https://utteranc.es/
  repo: nexmoe/books
	issue_term: title
	label: Comment
	theme: github-light

giscus: # https://giscus.app/
  repo: 
  repo_id: 
  category: 
  category_id: 
  mapping: title
  reactions_enabled: 1
  theme: light
  lang: zh-CN